GET http://localhost:3000/teste
Content-Type: application/json

###

GET http://localhost:3000/produto
Content-Type: application/json

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "email":"jonhenrilu@gmail.com",
    "password":"123"
}

###

GET http://localhost:3000/pratosdodia/2
Content-Type: application/json

###

POST http://localhost:3000/register
Content-Type: application/json

{
    "nome": "Jonathan Alves",
    "email": "jonhenrilu@gmail.com",
    "telefone":"925566577",
    "morada":"ali",
    "password":"123"
}
###

GET http://localhost:3000/usercount
Content-Type: application/json

###

GET http://localhost:3000/restaurantes
Content-Type: application/json

###

GET http://localhost:3000/categorias
Content-Type: application/json


###
GET http://localhost:3000/produtcategoria/1
Content-Type: application/json